aion_embeddings: data/processed/galaxy_embeddings_unified.parquet
aion_model: aion-base
batch_size: 8192
config: configs/baseline_original_exclude_benchmarks.yaml
device: null
embedding_dim: 1024
eval_frequency: 3
eval_names:
- lens_legacy
- lens_hsc
- mergers
- spirals
exclude_crossmatch: data/experiments/crossmatch_results/crossmatch_results_20250806_230911.csv
gradient_clip_max_norm: 1.0
learning_rate: 0.0001
log_level: INFO
max_train_samples: null
num_embedding: null
num_epochs: 50
output_dir: runs/train_clip_20250808_171624
save_checkpoint_frequency: 10
scheduler_eta_min: 5.0e-07
scheduler_t0: 50
scheduler_t_mult: 1
text_sampling_strategy: summaries-only
train_ratio: 0.8
use_mean_embeddings: true
use_multi_text: true
warmup_epochs: 10
weight_decay: 0.05
